#!/bin/bash

# Get the commit message from file, which just contains the message
commitMessage=$(cat $1)

# Ensure each commit message is formatted with a project key
#([^-]*-[^-]*)-.*
pattern="\[\d+\]\s[\w\s]+"
if [[ ! "$commitMessage" =~ $pattern  ]]; then
    echo "Please add an issue number to the commit message: $commitMessage"
    exit 1
fi
